function [images] = load_images()
    images_dir = '../images';
    image_names = {
        'zero.jpg', ...
        'one.jpg', ...
        'two.jpg', ...
        'three.jpg', ...
        'four.jpg', ...
        'five.jpg', ...
        'six.jpg', ...
        'seven.jpg', ...
        'eight.jpg', ...
        'nine.jpg'
    };
    images = {};
    for name = image_names
        image = imread(fullfile(images_dir, name{1}));
        image = rgb2gray(image);
        images{end + 1} = image;
    end
end
